FROM alpine
WORKDIR /app
RUN apk update && apk add nano && apk add git && apk add openssh-keygen
CMD git config --global user.name EliaSalerno
CMD git config --global user.email elia.salerno@issgreppi.it 
